name: Python CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - '**'

jobs:
  run_tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-20.04
        python-version: ['3.8', '3.11']
        toxenv: [django42]

    steps:
    - uses: actions/checkout@v3
    - name: setup python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: pip install -U pip tox wheel

    - name: Run Tests
      env:
        TOXENV: ${{ matrix.toxenv }}
      run: tox
